### ISSUE TITLE
read docs/builtin-doc.json fail

### ISSUE THREAD

**Issue by oblitum** [iamcco/vim-language-server#1]
I'm getting this error message when opening a vim file

```
builtin: [vimls]: read docs/builtin-doc.json fail => ENOENT: no such file or directory, open '/home/francisco/.yarn/docs/builtin-docs.json'
```

`builtin-docs.json` is missing, it looks like it couldn't be built.

```
~/.c/c/e/n/vim-language-server ❯❯❯ ./bin/build-docs.js
(node:10626) UnhandledPromiseRejectionWarning: TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at /home/francisco/.config/coc/extensions/node_modules/vim-language-server/out/script/build-docs.js:485:38
    at step (/home/francisco/.config/coc/extensions/node_modules/tslib/tslib.js:133:27)
    at Object.next (/home/francisco/.config/coc/extensions/node_modules/tslib/tslib.js:114:57)
    at /home/francisco/.config/coc/extensions/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/francisco/.config/coc/extensions/node_modules/tslib/tslib.js:103:16)
    at main (/home/francisco/.config/coc/extensions/node_modules/vim-language-server/out/script/build-docs.js:464:20)
    at Object.<anonymous> (/home/francisco/.config/coc/extensions/node_modules/vim-language-server/out/script/build-docs.js:544:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
(node:10626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iamcco** [comment]
Please update, should fix it.

**Comment by oblitum** [comment]
Perfect, thx.
