### ISSUE TITLE
UnhandledPromiseRejection on server start.

### ISSUE THREAD

**Issue by chemzqm** [iamcco/vim-language-server#5]
In log of coc.nvim I got this sometimes:

```
2019-07-01T12:48:01.074 DEBUG (pid:50716) [events] - Event: CursorHold [ 1 ]
2019-07-01T12:48:01.282 INFO (pid:50716) [services] - vim language server state change: starting => running
2019-07-01T12:48:01.284 DEBUG (pid:50716) [languages] - created service source vimlsp
2019-07-01T12:48:01.287 INFO (pid:50716) [services] - service vimlsp started
2019-07-01T12:48:01.288 DEBUG (pid:50716) [language-client-index] - [vimlsp] (node:50747) UnhandledPromiseRejectionWarning: Error: no parsers registered for: "
/usr"
    at parse (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_snapdragon@0.8.2@snapdragon/lib/parser.js:473:15)
    at Parser.parse (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_snapdragon@0.8.2@snapdragon/lib/parser.js:477:24)
    at Snapdragon.parse (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_snapdragon@0.8.2@snapdragon/index.js:122:28)
    at Snapdragon.<anonymous> (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/lib/utils.js:47:45)
    at parse (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/index.js:739:26)
    at memoize (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/index.js:859:13)
    at Function.micromatch.parse (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/index.js:745:10)
    at create (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/index.js:686:44)
    at /Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/index.js:695:16
    at memoize (/Users/chemzqm/.config/coc/extensions/node_modules/coc-vimlsp/node_modules/_micromatch@3.1.10@micromatch/index.js:859:13)
(node:50747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iamcco** [comment]
Can't reproduce the issue, therefor i catch the error and add log.

**Comment by iamcco** [comment]
fix by https://github.com/iamcco/vim-language-server/commit/6082d13814eb45deda6fa508befef2eeb2ee3de9
