### ISSUE TITLE
Server stopped without error message

### ISSUE THREAD

**Issue by mandos** [iamcco/vim-language-server#50]
My setup is:

```
NVIM v0.5.0-871-ga6bd52d
Native NeoVim LSP client
Configuration from neovim/nvim-lspconfig (dbb7396ecc6fa5325779ed8c1589c1c903de37b6)
configs[server_name] = {
  default_config = {
    cmd = {bin_name, "--stdio"},
    filetypes = {"vim"},
    root_dir = function(fname)
      return util.find_git_ancestor(fname) or vim.loop.os_homedir()
    end,
    init_options = {
      iskeyword = "@,48-57,_,192-255,-#",
      vimruntime = "",
      runtimepath = "",
      diagnostic = {enable = true},
      indexes = {
        runtimepath = true,
        gap = 100,
        count = 3,
        projectRootPatterns = {"runtime", "nvim", ".git", "autoload", "plugin"}
      },
      suggest = {fromVimruntime = true, fromRuntimepath = true}
    },
}
```
I run language server in docker with `docker exec -i vim-tools ...`

In LS client I see that server is initialized and response for one second but list of active clients is empty. Same as I start neovim with some "broken" vim files. Looks like server send at least one Diagnose message and then die.

My question: is any way to run logs on Server's side? Or maybe I can debug this problem in other way than just checking LS client logs?

**Comment by iamcco** [comment]
There is no way to run logs on server's side, you can open the log channel on the client side. you can also send the debug log to log channel. I don't know if it's normal for the neovim built-in LSP client that it does not show any error info when the server die.

**Comment by mandos** [comment]
> you can open the log channel on the client side. you can also send the debug log to log channel.
I'm not familiar with this methods, could you point me to the place where I can read about it, or give me some example how to do it?

**Comment by iamcco** [comment]
@mandos I'm not familiar either, I have not use neovim's built-in LSP client yet.

**Comment by mandos** [comment]
@iamcco I'm not sure if this helps but I got something like this
```
[ INFO ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:299 ]	"Starting RPC client"	{  args = { "--stdio" },  cmd = "vim-language-server",  extra = {}}
[ DEBUG ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:607 ]	"LSP[vimls]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "RefactorInline", "source.organizeImports", "quickfix", "QuickFix", "Refactor", "Source", "RefactorRewrite", "refactor.inline", "RefactorExtract", "source", "SourceOrganizeImports", "refactor", "Empty", "refactor.rewrite", "refactor.extract" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      <metatable> = <table 1>    }  },  initializationOptions = {    diagnostic = {      enable = true,      <metatable> = <table 1>    },    indexes = {      count = 3,      gap = 100,      projectRootPatterns = { "runtime", "nvim", ".git", "autoload", "plugin" },      runtimepath = true,      <metatable> = <table 1>    },    iskeyword = "@,48-57,_,192-255,-#",    runtimepath = "",    suggest = {      fromRuntimepath = true,      fromVimruntime = true,      <metatable> = <table 1>    },    vimruntime = "",    <metatable> = <table 1>  },  processId = 4606,  rootPath = "/home/mandos",  rootUri = "file:///home/mandos",  trace = "off"}
[ DEBUG ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "RefactorInline", "source.organizeImports", "quickfix", "QuickFix", "Refactor", "Source", "RefactorRewrite", "refactor.inline", "RefactorExtract", "source", "SourceOrganizeImports", "refactor", "Empty", "refactor.rewrite", "refactor.extract" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        <metatable> = <table 1>      }    },    initializationOptions = {      diagnostic = {        enable = true,        <metatable> = <table 1>      },      indexes = {        count = 3,        gap = 100,        projectRootPatterns = { "runtime", "nvim", ".git", "autoload", "plugin" },        runtimepath = true,        <metatable> = <table 1>      },      iskeyword = "@,48-57,_,192-255,-#",      runtimepath = "",      suggest = {        fromRuntimepath = true,        fromVimruntime = true,        <metatable> = <table 1>      },      vimruntime = "",      <metatable> = <table 1>    },    processId = 4606,    rootPath = "/home/mandos",    rootUri = "file:///home/mandos",    trace = "off"  }}
[ DEBUG ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      completionProvider = {        resolveProvider = true,        triggerCharacters = { ".", ":", "#", "[", "&", "$", "<", '"', "'" }      },      definitionProvider = true,      documentHighlightProvider = true,      documentSymbolProvider = true,      foldingRangeProvider = true,      hoverProvider = true,      referencesProvider = true,      renameProvider = {        prepareProvider = true      },      selectionRangeProvider = true,      signatureHelpProvider = {        triggerCharacters = { "(", "," }      },      textDocumentSync = 2    }  }}
[ DEBUG ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:633 ]	"LSP[vimls]"	"server_capabilities"	{  completionProvider = {    resolveProvider = true,    triggerCharacters = { ".", ":", "#", "[", "&", "$", "<", '"', "'" }  },  definitionProvider = true,  documentHighlightProvider = true,  documentSymbolProvider = true,  foldingRangeProvider = true,  hoverProvider = true,  referencesProvider = true,  renameProvider = {    prepareProvider = true  },  selectionRangeProvider = true,  signatureHelpProvider = {    triggerCharacters = { "(", "," }  },  textDocumentSync = 2}
[ INFO ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:634 ]	"LSP[vimls]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = false,    completion = true,    declaration = false,    document_formatting = false,    document_highlight = true,    document_range_formatting = false,    document_symbol = true,    execute_command = false,    find_references = true,    goto_definition = true,    hover = true,    implementation = false,    rename = true,    signature_help = true,    signature_help_trigger_characters = { "(", "," },    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = false,    text_document_save_include_text = false,    text_document_will_save = false,    text_document_will_save_wait_until = false,    type_definition = false,    workspace_symbol = false  }}
[ DEBUG ] 2020-11-26T22:19:01+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:376 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "vim",      text = "scriptencoding utf-8
\" Plugins{{{
\" Specify a directory for plugins:
\" for Neovim: ~/.local/share/nvim/plugged,
\" for Vim ~/.vim/plugged
call plug#begin('~/.local/share/nvim/plugged')
\" Autocomplete, snippets, tags
Plug 'neovim/nvim-lspconfig'
\" Initialize plugin system
call plug#end()
\"}}}

\" Lua syntax highlighting inside .vim files
let g:vimsyn_embed = 'l'

lua << EOF
  require'nvim-treesitter.configs'.setup {
  ensure_installed = \"maintained\", -- one of \"all\", \"maintained\" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
  }
  vim.lsp.set_log_level(\"trace\")
  local config=require'lspconfig'
  config.vimls.setup{}
  config.bashls.setup{}
EOF

noremap <leader>la :lua print(vim.inspect(vim.lsp))<CR>
noremap <leader>ls :lua vim.lsp.stop_client(vim.lsp.get_active_clients())<CR>
noremap <leader>lp :lua print(vim.inspect(vim.lsp.get_active_clients()))<CR>
",      uri = "file:///workspace/vim-plugins/init.vim",      version = 0    }  }}
[ DEBUG ] 2020-11-26T22:19:02+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:477 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///workspace/vim-plugins/init.vim"  }}
[ DEBUG ] 2020-11-26T22:19:02+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:472 ]	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "file:///workspace/vim-plugins/init.vim"}
[ DEBUG ] 2020-11-26T22:19:02+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:297 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 2,  params = {    diagnostics = {},    uri = "file:///workspace/vim-plugins/init.vim"  }}
[ ERROR ] 2020-11-26T22:19:04+0100 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]	"rpc"	"vim-language-server"	"stderr"	"events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:705:16)
    at SafeSubscriber.queue [as _next] (/usr/local/lib/node_modules/vim-language-server/out/scan.js:34898:17)
    at SafeSubscriber.__tryOrUnsub (/usr/local/lib/node_modules/vim-language-server/out/scan.js:23416:16)
    at SafeSubscriber.next (/usr/local/lib/node_modules/vim-language-server/out/scan.js:23354:22)
    at Subscriber._next (/usr/local/lib/node_modules/vim-language-server/out/scan.js:23300:26)
    at Subscriber.next (/usr/local/lib/node_modules/vim-language-server/out/scan.js:23277:18)
    at FilterSubscriber._next (/usr/local/lib/node_modules/vim-language-server/out/scan.js:28104:30)
    at FilterSubscriber.Subscriber.next (/usr/local/lib/node_modules/vim-language-server/out/scan.js:23277:18)
    at MergeMapSubscriber.notifyNext (/usr/local/lib/node_modules/vim-language-server/out/scan.js:27144:26)
    at InnerSubscriber._next (/usr/local/lib/node_modules/vim-language-server/out/scan.js:26730:21)
Emitted 'error' event on process instance at:
    at internal/child_process.js:709:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
"

```

**Comment by iamcco** [comment]
I have push a new version, please upgrade and have a test

**Comment by mandos** [comment]
@iamcco It's because I run vim-language-server in Docker's container. Installation on host machine works fine. Sorry for trouble, I will try to figure out myself why setup in container doesn't works.
