### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by hrqmonteiro** [iamcco/vim-language-server#51]
**Describe the bug**
Tried to install using both npm and yarn, and after it installed, it returns me this:

```
$vim-language-server --version

$ /usr/lib/node_modules/vim-language-server/out/index.js:882
        throw new Error('Connection input stream is not set. ' + commandLineMessage);
        ^

Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
    at _createConnection (/usr/lib/node_modules/vim-language-server/out/index.js:882:15)
    at Object.createConnection (/usr/lib/node_modules/vim-language-server/out/index.js:829:12)
    at Object.<anonymous> (/usr/lib/node_modules/vim-language-server/out/index.js:23246:46)
    at __webpack_require__ (/usr/lib/node_modules/vim-language-server/out/index.js:38699:42)
    at Object.defineProperty.value (/usr/lib/node_modules/vim-language-server/out/index.js:23216:20)
    at __webpack_require__ (/usr/lib/node_modules/vim-language-server/out/index.js:38699:42)
    at Object.<anonymous> (/usr/lib/node_modules/vim-language-server/out/index.js:14508:32)
    at __webpack_require__ (/usr/lib/node_modules/vim-language-server/out/index.js:38699:42)
    at Object.__assign (/usr/lib/node_modules/vim-language-server/out/index.js:14416:17)
    at __webpack_require__ (/usr/lib/node_modules/vim-language-server/out/index.js:38699:42)
```

**To Reproduce**
Install it using npm or yarn, then try to use it.

**Expected behavior**
Not returning me any errors.

**Desktop (please complete the following information):**
 - OS: Void Linux

**Comment by iamcco** [comment]
It's expected, `--version` options is not supported.

**Comment by iamcco** [comment]
Use `--stdio` options if you want to connect with stdio
